### ISSUE TITLE
Random attack enquiry

### ISSUE THREAD

**Issue by amblee0306** [KDDGRAND/grand#13]
Hi there, is it possible to get your code for random attack? I implemented my own version based upon my understanding but could not recover the mentioned ~37% reduction in performance for GAT and 12 % for GCN when 10% of random edges are added. I ensured that there is no duplicated edges in the set of added random edges. Also, I ensured that the random edges do not coincide with any edges in E on the graph G(V,E).

**Comment by wzfhaha** [comment]
> Hi there, is it possible to get your code for random attack? I implemented my own version based upon my understanding but could not recover the mentioned ~37% reduction in performance for GAT and 12 % for GCN when 10% of random edges are added. I ensured that there is no duplicated edges in the set of added random edges. Also, I ensured that the random edges do not coincide with any edges in E on the graph G(V,E).

Hi, thanks for your interest! I have uploaded our file for generating noisy edges. Please refer to [generate_noise_edge.py](https://github.com/THUDM/GRAND/blob/master/generate_noise_edge.py).

**Comment by amblee0306** [comment]
Hi there, 
Thanks for you quick reply. Would love to just double check a few more thing. 
I took a look at the script to generate the noisy edge and I assume that after running the script it will add 10% of noisy edges to G.

However, it seems that 10% perturbation is not just simply 10% of edges added, but adding 1 to 10% of edges.
For the case of Cora, at the beginning there is 13264 edges before adding any edges. But after adding 10% perturbation using the function in generate_noise_edge.py, it has 20554 edges. Is this expected? Cause I was expecting 10% edges to be added to mean 13264 --> 14590 edges only.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/19768905/177948371-cfb26543-4c4e-4dbe-abf1-ccd2f1d7fcf4.png">

Just to add on, I added the edges to the cora dataset and ran the GAT model example in the DGL library on it and the performance score is still at 70%.  Is there something else that I am missing?

**Comment by wzfhaha** [comment]
> Hi there, Thanks for you quick reply. Would love to just double check a few more thing. I took a look at the script to generate the noisy edge and I assume that after running the script it will add 10% of noisy edges to G.
> 
> However, it seems that 10% perturbation is not just simply 10% of edges added, but adding 1 to 10% of edges. For the case of Cora, at the beginning there is 13264 edges before adding any edges. But after adding 10% perturbation using the function in generate_noise_edge.py, it has 20554 edges. Is this expected? Cause I was expecting 10% edges to be added to mean 13264 --> 14590 edges only.
> 
> <img alt="image" width="293" src="https://user-images.githubusercontent.com/19768905/177948371-cfb26543-4c4e-4dbe-abf1-ccd2f1d7fcf4.png">
> 
> Just to add on, I added the edges to the cora dataset and ran the GAT model example in the DGL library on it and the performance score is still at 70%. Is there something else that I am missing?

Thanks for your advice. I have fixed the bug for generating noisy graphs. For the GAT model, I use the code from PYG, maybe there is some inconsistency with DGL.

**Comment by amblee0306** [comment]
Noted with thanks!
