### ISSUE TITLE
Questions about DropNode 

### ISSUE THREAD

**Issue by quqixun** [KDDGRAND/grand#7]
Questions:

1. The code did not scale features after dropping nodes randomly while training. It's not consist with paper.
2. Should it be original features as DropNode output during inference?
3. Should (1 - droprate) or 1 / (1 - droprate) be scale factor?

Description of DropNode in paper:
![image](https://user-images.githubusercontent.com/3949332/107143577-c9555b00-6970-11eb-82f2-e9d0ea740ce2.png)

Code of DropNode:
```python
if training:
    masks = torch.bernoulli(1. - drop_rates).unsqueeze(1)
    features = masks.cuda() * features  # did not scale features after dropping nodes randomly
else:
    features = features * (1. - drop_rate)  # scaled features during inference
```

**Comment by wzfhaha** [comment]
> Questions:
> 
> 1. The code did not scale features after dropping nodes randomly while training. It's not consist with paper.
> 2. Should it be original features as DropNode output during inference?
> 3. Should (1 - droprate) or 1 / (1 - droprate) be scale factor?
> 
> Description of DropNode in paper:
> ![image](https://user-images.githubusercontent.com/3949332/107143577-c9555b00-6970-11eb-82f2-e9d0ea740ce2.png)
> 
> Code of DropNode:
> 
> ```python
> if training:
>     masks = torch.bernoulli(1. - drop_rates).unsqueeze(1)
>     features = masks.cuda() * features  # did not scale features after dropping nodes randomly
> else:
>     features = features * (1. - drop_rate)  # scaled features during inference
> ```

Hi, thanks for your interests! DropNode/dropout can be implemented with two ways: 1) Scaling features with 1 / (1 - droprate) during training. 2) Scaling features with (1 - droprate) during inference. Our paper only describes the first method, but we implement it with the second.  Both methods are correct.
